# Generated by Django 5.2.4 on 2025-07-14 17:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_register_managers_register_date_joined_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('travel_date', models.DateField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='busticket',
            name='user',
        ),
        migrations.DeleteModel(
            name='NewRoute',
        ),
        migrations.RenameField(
            model_name='booking',
            old_name='booking_date',
            new_name='booked_at',
        ),
        migrations.RenameField(
            model_name='bus',
            old_name='operator',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='bus',
            old_name='origin',
            new_name='source',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='bus',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='seat_count',
        ),
        migrations.RemoveField(
            model_name='bus',
            name='departure_time',
        ),
        migrations.RemoveField(
            model_name='bus',
            name='price',
        ),
        migrations.RemoveField(
            model_name='bus',
            name='seats_available',
        ),
        migrations.AddField(
            model_name='booking',
            name='seat_number',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='bus',
            name='total_seats',
            field=models.PositiveIntegerField(default=40, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='schedule',
            name='bus',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.bus'),
        ),
        migrations.AddField(
            model_name='booking',
            name='schedule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.schedule'),
        ),
        migrations.DeleteModel(
            name='BusTicket',
        ),
    ]
